import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
    return (
        <div className="px-4 py-0">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="min-h-screen px-4 py-0 flex-1 flex flex-col justify-center items-center">
                <h1 className="text-center m-0 text-6xl font-bold">
                    Welcome to{' '}
                    <a className="text-blue-600" href="https://nextjs.org">
                        Next.js!
                    </a>
                </h1>

                <p className="my-16 text-2xl">
                    Get started by editing{' '}
                    <code className="font-mono text-xl bg-gray-50 p-3 rounded-md">
                        pages/index.js
                    </code>
                </p>

                <div className="flex item-center justify-center flex-wrap max-w-3xl">
                    <a
                        href="https://nextjs.org/docs"
                        className="m-4 p-6 text-left text-decoration-none text-inherit hover:text-blue-600 border border-gray-200 hover:border-blue-600 rounded-lg transition-colors duration-150 max-w-xs"
                    >
                        <h2 className="m-0 mb-4 text-2xl font-bold">Documentation &rarr;</h2>
                        <p className="m-0 text-xl">
                            Find in-depth information about Next.js features and API.
                        </p>
                    </a>

                    <a
                        href="https://nextjs.org/learn"
                        className="m-4 p-6 text-left text-decoration-none text-inherit hover:text-blue-600 border border-gray-200 hover:border-blue-600 rounded-lg transition-colors duration-150 max-w-xs"
                    >
                        <h2 className="m-0 mb-4 text-2xl font-bold">Learn &rarr;</h2>
                        <p className="m-0 text-xl">
                            Learn about Next.js in an interactive course with quizzes!
                        </p>
                    </a>

                    <a
                        href="https://github.com/vercel/next.js/tree/master/examples"
                        className="m-4 p-6 text-left text-decoration-none text-inherit hover:text-blue-600 border border-gray-200 hover:border-blue-600 rounded-lg transition-colors duration-150 max-w-xs"
                    >
                        <h2 className="m-0 mb-4 text-2xl font-bold">Examples &rarr;</h2>
                        <p className="m-0 text-xl">
                            Discover and deploy boilerplate example Next.js projects.
                        </p>
                    </a>

                    <a
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        className="m-4 p-6 text-left text-decoration-none text-inherit hover:text-blue-600 border border-gray-200 hover:border-blue-600 rounded-lg transition-colors duration-150 max-w-xs"
                    >
                        <h2 className="m-0 mb-4 text-2xl font-bold">Deploy &rarr;</h2>
                        <p className="m-0 text-xl">
                            Instantly deploy your Next.js site to a public URL with Vercel.
                        </p>
                    </a>
                </div>
            </main>

            <footer className="flex flex-1 py-8 border-t justify-center align-center">
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex justify-center align-center flex-grow"
                >
                    Powered by{' '}
                    <span className="h-4 ml-2">
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
